= Modchannels

Allows server side mods (SSMs) communication to client side mods (CSMs) and vice versa.

== Server Side API

=== Functions

==== minetest.mod_channel_join(channel_name)

* `channel_name`: string, modchannel name

Returns a object for use with <<Methods>>. Creates the channel if it does not exist and joins the channel.

==== minetest.register_on_modchannel_message(function(channel_name, sender, message))

* `channel_name`: string, modchannel name (already joined)
* `sender`: string, empty if from a ssm, player name if from a client
* `message`: string, message

=== Methods

NOTE: `channel` here means the object returned by `minetest.mod_channel_join`.

==== channel:leave()

The server will leave the channel, meaning no more messages from this channel on `minetest.register_on_modchannel_message`

TIP: set the channel to nil afterwords to free resources

==== channel:is_writeable()

* returns boolean, true if the channel is writeable

==== channel:send_all(message)

* `message`: string, limited to 65535 bytes

Sends to all SSMs and CSMs on the channel.

TIP: The message will drop if channel is not writable or invalid

== Client Side API

=== Functions

==== minetest.mod_channel_join(channel_name)

* `channel_name`: string, modchannel name

Returns a object for use with <<Methods>>. Creates the channel if it does not exist and joins the channel.

==== minetest.register_on_modchannel_message(function(channel_name, sender, message))

* `channel_name`: string, modchannel name (already joined and recieved acknowledgement)
* `sender`: string, empty if from a ssm, player name if from a client
* `message`: string, message

==== minetest.register_on_modchannel_signal(function(channel_name, signal))
* `channel_name`: string, channel name that the signal has come in on
* `signal`: integer, 0 - 5
[start=0]
. join_ok
. join_failed
. leave_ok
. leave_failed
. event_on_not_joined_channel
. state_changed

=== Methods

NOTE: `channel` here means the object returned by `minetest.mod_channel_join`.

==== channel:leave()

The server will leave the channel, meaning no more messages from this channel on `minetest.register_on_modchannel_message`

TIP: set the channel to nil afterwords to free resources

==== channel:is_writeable()

* returns boolean, true if the channel is writeable

==== channel:send_all(message)

* `message`: string, limited to 65535 bytes

Sends to all SSMs and CSMs on the channel.

TIP: The message will drop if channel is not writable or invalid