= Object Properties
include::../include/config.adoc[]
:url-c-content-src: {url-engine-src}/script/common/c_content.cpp[]

WARNING: There may be missing/incorrect information here,
please refer to the {url-lua-api}#L7141-L7304[Lua API]
and the {url-c-content-src}#L186-L442[relevant engine code]

WARNING: This is missing the default values for everything

== `player` only

=== `hp_max`
* internal type: `u16`

Sets the max HP of a player.

=== `breath_max`
* internal type: `u16`

Sets the max breath of a player.

=== `eye_height`
* internal type: `unknown`

How high the camera is in nodes about the player's feet.

=== `zoom_fov`
* internal type: `unknown`

Not sure.

== All

=== `physical`
* field type: `bool`

Collides with nodes that are `walkable`.

=== `collide_with_objects`
* field type: `bool`

Collides with other objects.
CAUTION: `physical` must be set to `true` for this to take effect!

=== `collisionbox`
TIP: This could maybe be linked somewhere else.

* field type: `cuboid_def`

The collision box of an object. Wanted value is `{xmin, ymin, zmin, xmax, ymax, zmax}` (in nodes from the center of the object/ object position).

=== `selectionbox`
* field type: `cuboid_def`

The selection box of an object, if not set, uses `collisionbox`. Wanted value is `{xmin, ymin, zmin, xmax, ymax, zmax}` (in nodes from the object).

=== `pointable`
* field type: `bool`

Whether the object can be pointed at.

=== `visual`
* field type: `unknown`

Not sure.

=== `mesh`
* field type: `string`

Not sure.

=== `visual_size`
* field type: `3d_vector`

Visual size multipliers. Wanted value is `vector` (`{x = x, y = y, z = z}`), if `z` is not provided, `x` will be used for the `z` value.

=== `textures`
* field type: `{string, string, ...}`

Wanted value is `{"texture.png", "texture.png", ...}`. The number of textures depends on `visual`.

=== `colors`
* field type: `unknown`

Not sure

=== `spritediv`
* field type: `2d_vector`

Not sure. Wanted value is `{x = x, y = y}`.

=== `initial_sprite_basepos`
* field type: `2d_vector`

Not sure. Wanted value is `{x = x, y = y}`.

=== `is_visible`
* field type: `bool`

Whether the object is visible and can be pointed at.

=== `makes_footstep_sound`
* field type: `bool`

Whether the object makes a footstep sound when it steps on nodes that that have footstep sounds.

=== `stepheight`
* internal type: `f32`

How high in nodes the object can step up.

=== `automatic_rotate`
* internal type: `f32`

How high in nodes the object can step up.

=== `automatic_face_movement_dir`
* field type: `int` or `false`

TIP: This property can be set to `false` to disable it.

Not sure.

=== `backface_culling`
* field type: `bool`

Whether or not a model is backface culled.

=== `glow`
* field type: `int`

=== `nametag`
* field type: `string`

Text displayed about an object, empty by default for all objects except players, in which case, it is their name.

=== `nametag_color`
* field type: `color_def` or `false`
* internal type: `ColorSpec`

The color that the nametag text will be.
TIP: This property can be set to `false` to disable it.

=== `nametag_bgcolor`
* field type: `color_def` or `false`
* internal type: `ColorSpec`

TIP: This property can be set to `false` to disable it.

=== `automatic_face_movement_max_rotation_per_sec`
* field type: `unknown`

Not sure.

=== `infotext`
* field type: `string`

When a player points at the object, they will be shown the text.

=== `static_save`
* field type: `bool`

Whether the object is saved  statically, if not, it will be deleted when the world block is unloaded.

=== `wield_item`
* internal type: `ItemString`

=== `use_texture_alpha`
* field type: `bool`

Whether or not the texture's alpha should be used.

=== `shaded`
* field type: `bool`

Whether or not diffuse lighting is enabled for the object.

=== `show_on_minimap`
* field type: `bool`

Whether or not the object is visible on the minimap.

=== `damage_texture_modifier`
* field type: `string`

A texture modifier that will be appended to the object's current textures for the duration of the damage flash when the object is damaged.

