= Object Properties
include::../include/config.adoc[]
:description: Documentaton of Object Properties
:keywords: obj, props, object, properties
:url-c-content-src: {url-engine-src}/script/common/c_content.cpp

WARNING: There may be missing/incorrect information here,
please refer to the {url-lua-api}#L7141-L7304[Lua API]
and the {url-c-content-src}#L186-L442[relevant engine code]

WARNING: This is missing the default values for everything

== Properties Applying Only to Players

=== `hp_max`
* internal type: `u16`

Sets the max HP of a player.
Clamped if it goes above the `u16` max value or under the `u16` min value.

=== `breath_max`
* internal type: `u16`

Sets the max breath of a player.

=== `eye_height`
* internal type: `f32`

How high the camera is in nodes about the player's feet.

=== `zoom_fov`
* internal type: `f32`
* units: `degrees`

Sets the field of view of the player when they zoom. Setting to `0` disables zooming.

== Properties Applying to All Objects

=== `physical`
* field type: `bool`

Whether the object collides with nodes that are `walkable`.

=== `collide_with_objects`
* field type: `bool`

Controls whether the object collides with other objects.

CAUTION: `physical` must be set to `true` for this to take effect!

=== `collisionbox`
//TIP: This could maybe be linked somewhere else.

* field type: `cuboid_def`

The collision box of an object. Wanted value is `{xmin, ymin, zmin, xmax, ymax, zmax}` (in nodes from the center of the object/ object position).

=== `selectionbox`
* field type: `cuboid_def`

The selection box of an object, if not set, uses `collisionbox`. Wanted value is `{xmin, ymin, zmin, xmax, ymax, zmax}` (in nodes from the center of the object/ object position).

=== `pointable`
* field type: `bool`

Controls whether the object can be pointed at.

=== `visual`
* field type: `string`

Possible values:

* `"cube"`: A cube that has the same size as a normal node
* `"item"`: similar to `wielditem`, but ignores the `wield_item` property
* `"mesh"`: Use a mesh model, see the `mesh` property 
* `"sprite"`: A texture that is flat and always faces the player
* `"upright_sprite"`: A texture that is flat and faces upright
* `"wielditem"`: Used for dropped items, see the `wield_item` property

Sets what the object will look like.

TIP: The `"wielditem"` value supports hardware colorization

=== `mesh`
* field type: `string`

Name of the file of the mesh, only when using "mesh" visual.

=== `visual_size`
* field type: `vector`

Visual size multipliers. Wanted value is `{x = x, y = y, z = z}`, if `z` is not provided, `x` will be used for the `z` value.

=== `textures`
* field type: `string list`

Wanted value is `{"texture.png", "texture.png", ...}`. The number of textures depends on `visual`:

* "cube": 6 textures
* "mesh": 1 texture for each mesh material
* "sprite": 1 texture
* "upright_sprite": 2 textures

=== `colors`
* internal type: `ColorSpec table`

CAUTION: This feature is not functional.

=== `spritediv`
* field type: `2d_vector`

Determines the number of columns, rows in a spritesheet texture, which is used for animations.. Wanted value is `{x = columns, y = rows}`.

=== `initial_sprite_basepos`
* field type: `2d_vector`

Determines the position of the first frame to use in the spritesheet texture. Wanted value is `{x = column, y = row}`.

=== `is_visible`
* field type: `bool`

Whether the object is visible and can be pointed at.

=== `makes_footstep_sound`
* field type: `bool`

Whether the object makes a footstep sound when it steps on nodes that that have footstep sounds.

=== `stepheight`
* internal type: `f32`

How high in nodes the object can step up.

=== `automatic_rotate`
* internal type: `f32`

How fast the object automatically rotates along the `y` axis in radians/second.

=== `automatic_face_movement_dir`
* field type: `int` or `false`
* unit: `degrees`

TIP: This property can be set to `false` to disable it.

Make the object automatically face the direction it is moving in, the value is the offset in degrees.

=== `backface_culling`
* field type: `bool`

Whether a model is backface culled (the faces of the model who's backs are towards a player aren't rendered).

=== `glow`
* field type: `int`

When calculating the texture color, add this much lighting. Maximum value is `minetest.LIGHT_MAX`.

=== `nametag`
* field type: `string`

Text displayed about an object, empty by default for all objects except players, in which case, it is their name.

=== `nametag_color`
* internal type: `ColorSpec`

The color that the nametag text will be.

TIP: This property can be set to `false` to disable it.

=== `nametag_bgcolor`
* field type: `color_def` or `false`
* internal type: `ColorSpec`

The color that the nametag's background will be.

TIP: This property can be set to `false` to disable it.

=== `automatic_face_movement_max_rotation_per_sec`
* field type: `int`

Cap the automatic rotation to this value. If the value is less than or equal to 0, there will be no maximum.

=== `infotext`
* field type: `string`

When a player points at the object, they will be shown the text.

=== `static_save`
* field type: `bool`

Whether the object is saved  statically, if not, it will be deleted when the world block is unloaded.

=== `wield_item`
* internal type: `ItemString`

Only when using "wielditem" visual

=== `use_texture_alpha`
* field type: `bool`

Whether or not the texture's alpha should be used.

=== `shaded`
* field type: `bool`

Whether or not diffuse lighting is enabled for the object.

=== `show_on_minimap`
* field type: `bool`

Whether or not the object is visible on the minimap.

=== `damage_texture_modifier`
* field type: `string`

A texture modifier that will be appended to the object's current textures for the duration of the damage flash when the object is damaged.

== Layout of Object Properties

The way these properties are laid out is in a table.

NOTE: Extraneous properties will be ignored, but might be interpreted incorrectly by furutre versions of the engine, which is why it is recommended to prefix them with an underscore.

NOTE: This uses regular indexing so metatables work as expected.

== Example

[source,lua]
----
{
    hp_max = 10,
    breath_max = 5,
    eye_height = 0.8,
    zoom_fov = 0,
    physical = true,
    collide_with_objects = true,
    collisionbox = {-0.3, -0.3, -0.3, 0.3, 0.3, 0.3},
    selectionbox = {-0.3, -0.3, -0.3, 0.3, 0.3, 0.3},
    pointable = true,
    visual = "mesh",
    mesh = "mesh.obj",
    visual_size = {x = 1, y = 1, z = 1},
    textures = {"texture.png", "texture.png"},
    colors = {},
    spritediv = {x = 1, y = 1},
    initial_sprite_basepos = {x = 0, y = 0},
    is_visible = true,
    makes_footstep_sound = true,
    stepheight = 0.4,
    automatic_rotate = 0.0,
    automatic_face_movement_dir = 0,
    backface_culling = true,
    glow = 0,
    nametag = "My object",
    nametag_color = {r = 255, g = 255, b = 255},
    nametag_bgcolor = {r = 0, g = 0, b = 0},
    automatic_face_movement_max_rotation_per_sec = 0,
    infotext = "Hello there!",
    static_save = true,
    wield_item = "",
    use_texture_alpha = true,
    shaded = true,
    show_on_minimap = true,
    damage_texture_modifier = "^[colorize:#FF0000:150",
}
----
