= ModStorage

include::../include/config.adoc[]
include::../include/types.adoc[]
:description: Per-mod persistent key-value store
:keywords: meta, data, metadata, mod, storage, key, value, persistence

ModStorage is a per-world, per-mod persistent string key-value store implementing all methods of MetaData.

The granularity of the persisted snapshots is determined by the `map_save_interval` setting.

WARNING: Incapable of saving raw binary data due to JSON restrictions.

NOTE: It is usually more efficient to leverage the key-value store
than to store fully serialized data structures; fully serializing the data takes linear time
in the size of the data whereas updating the key-value store only takes linear time
in the size of the delta with the new SQLite3 backend. 

== `minetest.get_mod_storage()`

Must be called at load time.

=== Returns

[%autowidth, frame=none]
|===
| `storage` | ModStorage | Private ModStorage object for the currently loading mod
|===

=== Example

A basic greeting mod with a persistent greeting might look as follows:

[source,lua]
----
local storage = minetest.get_mod_storage()

-- Send the greeting to joining players
minetest.register_on_joinplayer(function(player)
	local greeting = storage:get"greeting"
	if greeting then
		minetest.chat_send_player(player:get_player_name(), greeting)
	end
end)

-- Allow moderators to change the greeting
minetest.register_chatcommand("/set_greeting", {
	params = "<greeting>",
	description = "Sets the greeting",
	privs = {server = true},
	func = function(name, param)
		param = param:trim() -- MT-provided string.trim
		storage:set_string("greeting", param)
		return true, param == "" and "Greeting cleared." or "Greeting set."
	end
})
----
