= `Vehicle`
include::../include/config.adoc[]
:description: The standard style template for documentation.
:keywords: standard, template

This is the standard template of how a good AsciiDoc should be structured.
This pragraph describes the purpose of the document.
In this example, an imaginary API for a vehicle will be documented.

== `Vehicle` Properties

=== `make: string`
The make of the vehicle.

=== `model: string`
The model of the vehicle.

=== `year: number`
The year of the vehicle.

=== `trim: string`
The trim of the vehicle.

=== `color: ColorSpec`
The color of the vehicle.

== `Vehicle` Methods

=== `vehicle.new(pos: vector, properties: table) -> Vehicle`
* `pos`: The position at which the vehicle will be spanwed.
* `properties`: A `table` of Vehicle properties (link).

Creates a new instance of a `Vehicle` at the given position and returns the new object.

.Creating a Vehicle
====

[source,lua]
----
local minivan = vehicle.new(vector.new(35, 2, 36), {
    make = "Toyota",
    model = "Previa",
    year = 1992,
    trim = "LE",
    color = "white",
})
----

====

=== `set_properties(properties: table)`
* `properties`: A `table` of Vehicle properties (link).

Sets the properties of the vehicle.

=== `get_properties() -> table`

Returns a `table` of Vehicle properties (link).

=== `set_pos(pos: vector)`
* `pos`: Where to place the vehicle.

=== `get_pos() -> vector`

Returns the position of the vehicle.

=== `set_gear(gear: number) -> boolean`
* `gear`: The gear to shift to. Should be one of
    ** `-1`: Reverse
    ** `0`: Park
    ** `1` - `3`: First - third gear

Returns `true` upon success, `false` otherwise.

=== `get_gear() -> number`

Returns the current gear of the vehicle as a number. See `set_gear` for expected values (link).

== Global `Vehicle` Functions

=== `gear_to_name(gear: number) -> string`
* `gear`: The gear number to convert.

Returns the name of the given gear. Expected return values:

* `-1`: `reverse`
* `0`: `park`
* `1`: `first`
* `2`: `second`
* `3`: `third`

=== `is_electric(make: string, model: string, year: number) -> boolean`
* `make`: The make of the vehicle.
* `model`: The model of the vehicle.
* `year`: The year of the vehicle.

Returns `true` if the given vehicle is electric, `false` otherwise.

.Checking an Electric Vehicle
====

[source,lua]
----
local ev = is_electric("Toyota", "Previa", 1992) -- false
----

====

Made with https://asciidoctor.org/[AsciiDoctor] | Contribute on {url-docs-repo}[GitHub]
